services:
  redis:
    image: redis:8-alpine
    container_name: adonis-jobs-redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    environment:
      - REDIS_ARGS=--save 60 1000 --loglevel warning
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  redis_data:
    driver: local
