global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'adonis-jobs'
    static_configs:
      - targets: ['localhost:3333']
    scrape_interval: 5s
    scrape_timeout: 4s
    metrics_path: '/metrics'
