name: Check

on: [push]

env:
  BULLMQ_PRO_TOKEN: ${{ secrets.BULLMQ_PRO_TOKEN }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup environment
        uses: ./.github/actions/setup
        with:
          node-version: 24
      - name: Run lint
        run: pnpm run lint

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup environment
        uses: ./.github/actions/setup
        with:
          node-version: 24
      - name: Run typecheck
        run: pnpm run typecheck

  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version:
          - 22.x
          - 24.x

    steps:
      - uses: actions/checkout@v4
      - name: Setup environment
        uses: ./.github/actions/setup
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run tests
        run: pnpm test
